### ISSUE TITLE
Share your own router page

### ISSUE THREAD

**Issue by sirjo66** [FluxionNetwork/sites#1]
Hi all,
I want to share my own router page, so I type:
`cd scripts`
`sudo sh router.sh`
It works and it create a folder with all the files.
...... and now ??
How can I send to you the files ??
Many thanks
Sergio

**Comment by MPX4132** [comment]
After it's been created, you need to store the page in `fluxion/attacks/Captive Portal/sites`, then you need to commit your changes and create a merge/pull request. If possible, you can make the page functional yourself with the [wiki article here](https://github.com/FluxionNetwork/fluxion/wiki/Prepping-protals-for-fluxion), otherwise just commit and do the request. I can't help you with git, you're going to have to look that up yourself if you don't know how to use it. It's pretty simple, so don't freak out.
